### ISSUE TITLE
OOM occurs when running the whisper model

### ISSUE THREAD

**Issue by Helshr** [hans00/react-native-transformers-example#15]
Could not invoke Onnxruntime.run. Failed to allocate a 54000015 byte allocation with 25165824 free bytes and 41MB until OOM, target foorprint 249685672, growth limit 268435456

**Comment by Helshr** [comment]
AndroidManifest.xml:


<manifest xmlns:android="http://schemas.android.com/apk/res/android">

    <uses-permission android:name="android.permission.INTERNET" />

    <application
      android:name=".MainApplication"
      android:label="@string/app_name"
      android:icon="@mipmap/ic_launcher"
      android:roundIcon="@mipmap/ic_launcher_round"
      android:allowBackup="false"
      android:theme="@style/AppTheme"
      android:largeHeap="true"
      android:hardwareAccelerated="false"
      >
      <activity
        android:name=".MainActivity"
        android:label="@string/app_name"
        android:configChanges="keyboard|keyboardHidden|orientation|screenLayout|screenSize|smallestScreenSize|uiMode"
        android:launchMode="singleTask"
        android:windowSoftInputMode="adjustResize"
        android:exported="true">
        <intent-filter>
            <action android:name="android.intent.action.MAIN" />
            <category android:name="android.intent.category.LAUNCHER" />
        </intent-filter>
      </activity>
    </application>
</manifest>

**Comment by hans00** [comment]
What device do you use

**Comment by hans00** [comment]
The OOM might be model is too large for your device.
